In [1]:
import numpy as np
arr = np.empty(10, dtype=object)
print(arr)

[None None None None None None None None None None]


In [2]:
import numpy as np
arr = np.array([4, 3, 2, 1])
print(arr)

[4 3 2 1]


In [3]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],
[10, 11, 12]]])
print(arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
data_siswa=[[132,133,134],[1,1,3]]
print(data_siswa)

[[132, 133, 134], [1, 1, 3]]


In [6]:
data_siswa = [[132, 133, 134],[1, 3], ["Dono",
"Kasino", "Indro"]]
print(data_siswa)

[[132, 133, 134], [1, 3], ['Dono', 'Kasino', 'Indro']]


In [7]:
import numpy as np
arr = np.array([4, 3, 2, 1])
print(arr[1])

3


In [8]:
import numpy as np
arr = np.array([4, 3, 2, 1])
for x in arr:
 print(x)


4
3
2
1


In [9]:
import numpy as np
arr = np.array([4, 3, 2, 1])
print(arr[1])
arr[1] = 10;
print(arr[1])


3
10


In [10]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,1])

7


In [12]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,1])
arr[1][1] = 100;
print(arr[1,1])

7
100


In [13]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],
[10, 11, 12]]])
print(arr[0, 1, 2])

6


In [14]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],
[10, 11, 12]]])
print(arr[0, 1, 2])
arr[0][1][2] = 100;
print(arr[0, 1, 2])


6
100


In [17]:
data_siswa=[[132,133,134],[1,1,3]]
print(data_siswa)

[[132, 133, 134], [1, 1, 3]]


In [18]:
data_siswa=[[132, 133, 134],[1, 3], ["Dono",
"Kasino", "Indro"]]
print(data_siswa[2][1])


Kasino


In [23]:
data_siswa=[[132, 133, 134],[1, 3], ["Dono", "Kasino", "Indro"]]
print(data_siswa[2][1])
data_siswa[2][1] = "Ketut"
print(data_siswa[2][1]);


Kasino
Ketut


In [24]:
import numpy as np
arrku = np.array([1,2,3,4,5])
print("Nilai minimal = ", arrku.min())
print("Nilai maksimal = ", arrku.max())
print("Nilai rata-rata = ", arrku.mean())
print("Total nilai = ", arrku.sum())
print("Standar Deviasi = ", arrku.std())

Nilai minimal =  1
Nilai maksimal =  5
Nilai rata-rata =  3.0
Total nilai =  15
Standar Deviasi =  1.4142135623730951
